// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibnseiaxlmevrnwonrhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlibnNlaWF4bG1ldnJud29ucmhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MDQ5ODcsImV4cCI6MjA1ODQ4MDk4N30.0QFcdVaLk0h9IhDBV6jpRt5wImzOUAnBaaunz5D8bLw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);